#!/usr/bin/env python3
"""Write Supabase URL and anon key into assets/js/config.js."""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_PATH = os.path.join(ROOT, "assets", "js", "config.js")


def main() -> None:
    parser = argparse.ArgumentParser(description="Configure Supabase credentials for Zeolite Ring.")
    parser.add_argument("--url", required=True, help="Supabase Project URL")
    parser.add_argument("--anon-key", required=True, help="Supabase anon public key")
    args = parser.parse_args()

    url = args.url.strip().rstrip("/")
    anon_key = args.anon_key.strip()

    if not url.startswith("https://") or ".supabase.co" not in url:
        print("Error: URL should look like https://xxxx.supabase.co", file=sys.stderr)
        sys.exit(1)
    if not anon_key.startswith("eyJ") and not anon_key.startswith("sb_publishable_"):
        print("Warning: key should be anon (eyJ...) or publishable (sb_publishable_...)", file=sys.stderr)

    content = f"""/**
 * Supabase configuration.
 * Generated by scripts/configure_supabase.py
 */
window.__SUPABASE_CONFIG__ = {{
  url: "{url}",
  anonKey: "{anon_key}",
}};
"""

    with open(CONFIG_PATH, "w", encoding="utf-8") as handle:
        handle.write(content)

    print(f"Updated {CONFIG_PATH}")
    print("\nNext steps:")
    print("1. Supabase Dashboard → Authentication → URL Configuration")
    print("   Set Site URL + Redirect URLs to your Cloudflare Pages domain")
    print("2. Enable Google + Email providers")
    print("3. git add assets/js/config.js && git commit && git push")


if __name__ == "__main__":
    main()
